### ISSUE TITLE
Put each variable in a different split

### ISSUE THREAD

**Issue by haimasree** [haimasree/esgfdownloader#5]
Requested by @lshendrik 
f.e.
'va_day_CanESM5_historical_r15i1p1f1_gn_20010101-20101231.nc' .....
'va_day_CanESM5_historical_r15i1p1f1_gn_20110101-20141231.nc' ......
'vas_day_CanESM5_historical_r15i1p1f1_gn_18500101-20141231.nc' .....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18500101-18601231.nc' .....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18610101-18701231.nc' ....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18710101-18801231.nc' ....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18810101-18901231.nc' ....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18910101-19001231.nc' ....

From this list, each file starts with variable name, and after the split I want each wget to contain only 1 variable.
Another option is to define two groups of variables, and use them also while splitting
F.e. splitted file can include either : tas, psl, vas and uas variables or  ta, zg, va and ua,  but not a mix of them

**Comment by haimasree** [comment]
@lshendrik  Can you verify if this is what you want?
An example command will be great. My thought is 
```split -v1  tas, psl, vas, uas   -v2 ta, zg, va, ua``` will produce two files. 
The first file will contain 
```
'va_day_CanESM5_historical_r15i1p1f1_gn_20010101-20101231.nc' .....
'va_day_CanESM5_historical_r15i1p1f1_gn_20110101-20141231.nc' .....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18500101-18601231.nc' .....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18610101-18701231.nc' ....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18710101-18801231.nc' ....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18810101-18901231.nc' ....
'zg_day_CanESM5_historical_r15i1p1f1_gn_18910101-19001231.nc' ....
```
and the second file will contain
```
'vas_day_CanESM5_historical_r15i1p1f1_gn_18500101-20141231.nc' .....
```
?

**Comment by lshendrik** [comment]
Yes, exactly like this

**Comment by haimasree** [comment]
Okay! I will work on it asap.
